import type { LessonItem } from './types';

export const MOCK_LESSONS: LessonItem[] = [
  {
    id: '1',
    disciplineName: 'Машинне навчання та штучний інтелект',
    teacherName: 'Котов Р.О.',
    lessonNumber: 3,
    startsAt: '11:25',
    endsAt: '12:45',
    weekday: 1,
    weekType: 'NUMERATOR',
    format: 'ONLINE',
    meetingUrl: 'https://meet.google.com',
  },
  {
    id: '2',
    disciplineName: 'Машинне навчання та штучний інтелект',
    teacherName: 'Котов Р.О.',
    lessonNumber: 4,
    startsAt: '12:55',
    endsAt: '14:15',
    weekday: 1,
    weekType: 'NUMERATOR',
    format: 'ONLINE',
    meetingUrl: 'https://meet.google.com',
  },
  {
    id: '3',
    disciplineName: 'Машинне навчання та штучний інтелект',
    teacherName: 'Котов Р.О.',
    lessonNumber: 5,
    startsAt: '14:30',
    endsAt: '15:50',
    weekday: 1,
    weekType: 'NUMERATOR',
    format: 'ONLINE',
    meetingUrl: 'https://meet.google.com',
  },
  {
    id: '4',
    disciplineName: 'Машинне навчання та штучний інтелект',
    teacherName: 'Котов Р.О.',
    lessonNumber: 3,
    startsAt: '11:25',
    endsAt: '12:45',
    weekday: 2,
    weekType: 'NUMERATOR',
    format: 'ONLINE',
    meetingUrl: 'https://meet.google.com',
  },
  {
    id: '5',
    disciplineName: 'Машинне навчання та штучний інтелект',
    teacherName: 'Котов Р.О.',
    lessonNumber: 4,
    startsAt: '12:55',
    endsAt: '14:15',
    weekday: 2,
    weekType: 'NUMERATOR',
    format: 'ONLINE',
    meetingUrl: 'https://meet.google.com',
  },
  {
    id: '6',
    disciplineName: 'Машинне навчання та штучний інтелект',
    teacherName: 'Котов Р.О.',
    lessonNumber: 5,
    startsAt: '14:30',
    endsAt: '15:50',
    weekday: 2,
    weekType: 'NUMERATOR',
    format: 'ONLINE',
    meetingUrl: 'https://meet.google.com',
  },
  {
    id: '7',
    disciplineName: 'Машинне навчання та штучний інтелект',
    teacherName: 'Котов Р.О.',
    lessonNumber: 2,
    startsAt: '9:35',
    endsAt: '10:55',
    weekday: 3,
    weekType: 'NUMERATOR',
    format: 'ONLINE',
    meetingUrl: 'https://meet.google.com',
  },
  {
    id: '8',
    disciplineName: 'Машинне навчання та штучний інтелект',
    teacherName: 'Котов Р.О.',
    lessonNumber: 3,
    startsAt: '11:25',
    endsAt: '12:45',
    weekday: 3,
    weekType: 'NUMERATOR',
    format: 'ONLINE',
    meetingUrl: 'https://meet.google.com',
  },
  {
    id: '9',
    disciplineName: 'Машинне навчання та штучний інтелект',
    teacherName: 'Котов Р.О.',
    lessonNumber: 4,
    startsAt: '12:55',
    endsAt: '14:15',
    weekday: 3,
    weekType: 'NUMERATOR',
    format: 'ONLINE',
    meetingUrl: 'https://meet.google.com',
  },
  {
    id: '10',
    disciplineName: 'Машинне навчання та штучний інтелект',
    teacherName: 'Котов Р.О.',
    lessonNumber: 2,
    startsAt: '9:35',
    endsAt: '10:55',
    weekday: 4,
    weekType: 'NUMERATOR',
    format: 'ONLINE',
    meetingUrl: 'https://meet.google.com',
  },
  {
    id: '11',
    disciplineName: 'Машинне навчання та штучний інтелект',
    teacherName: 'Котов Р.О.',
    lessonNumber: 3,
    startsAt: '11:25',
    endsAt: '12:45',
    weekday: 4,
    weekType: 'NUMERATOR',
    format: 'ONLINE',
    meetingUrl: 'https://meet.google.com',
  },
  {
    id: '12',
    disciplineName: 'Машинне навчання та штучний інтелект',
    teacherName: 'Котов Р.О.',
    lessonNumber: 4,
    startsAt: '12:55',
    endsAt: '14:15',
    weekday: 4,
    weekType: 'NUMERATOR',
    format: 'ONLINE',
    meetingUrl: 'https://meet.google.com',
  },
  {
    id: '13',
    disciplineName: 'Машинне навчання та штучний інтелект',
    teacherName: 'Котов Р.О.',
    lessonNumber: 2,
    startsAt: '9:35',
    endsAt: '10:55',
    weekday: 5,
    weekType: 'NUMERATOR',
    format: 'ONLINE',
    meetingUrl: 'https://meet.google.com',
  },
  {
    id: '14',
    disciplineName: 'Машинне навчання та штучний інтелект',
    teacherName: 'Котов Р.О.',
    lessonNumber: 3,
    startsAt: '11:25',
    endsAt: '12:45',
    weekday: 5,
    weekType: 'NUMERATOR',
    format: 'ONLINE',
    meetingUrl: 'https://meet.google.com',
  },
  {
    id: '15',
    disciplineName: 'Бази даних',
    teacherName: 'Мельник А.С.',
    lessonNumber: 3,
    startsAt: '11:25',
    endsAt: '12:45',
    weekday: 1,
    weekType: 'DENOMINATOR',
    format: 'OFFLINE',
    room: 'Ауд. 318',
  },
];