import type { CalendarEvent } from './types';

export const MOCK_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 1,
    title: 'тест з математики',
    date: '2026-09-01',
    type: 'DEADLINE',
    discipline: 'Вища математика',
    description: 'Підсумкове тестування за розділом 1',
    linkUrl: 'https://classroom.google.com',
  },
  {
    id: 2,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-01',
    type: 'EVENT',
    description: 'Святковий захід до Дня знань',
    time: '21.09.2198',
  },
  {
    id: 3,
    title: 'тест з математики',
    date: '2026-09-04',
    type: 'DEADLINE',
    discipline: 'Вища математика',
    description: 'Самостійна робота',
    linkUrl: 'https://classroom.google.com',
  },
  {
    id: 4,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-04',
    type: 'EVENT',
    description: 'Святковий захід для студентів',
    time: '21.09.2198',
  },
  {
    id: 5,
    title: 'Консультація перед іспитом',
    date: '2026-09-04',
    type: 'EVENT',
    description: 'Питання та відповіді',
  },
  {
    id: 6,
    title: 'тест з математики',
    date: '2026-09-05',
    type: 'DEADLINE',
    discipline: 'Дискретна математика',
  },
  {
    id: 7,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-05',
    type: 'EVENT',
  },
  {
    id: 8,
    title: 'тест з математики',
    date: '2026-09-06',
    type: 'DEADLINE',
    discipline: 'Математичний аналіз',
  },
  {
    id: 9,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-06',
    type: 'EVENT',
  },
  {
    id: 10,
    title: 'тест з математики',
    date: '2026-09-08',
    type: 'DEADLINE',
  },
  {
    id: 11,
    title: 'Збори студради',
    date: '2026-09-08',
    type: 'EVENT',
  },
  {
    id: 12,
    title: 'тест з математики',
    date: '2026-09-09',
    type: 'DEADLINE',
  },
  {
    id: 13,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-09',
    type: 'EVENT',
  },
  {
    id: 14,
    title: 'тест з математики',
    date: '2026-09-10',
    type: 'DEADLINE',
  },
  {
    id: 15,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-10',
    type: 'EVENT',
  },
  {
    id: 16,
    title: 'тест з математики',
    date: '2026-09-13',
    type: 'DEADLINE',
  },
  {
    id: 17,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-13',
    type: 'EVENT',
  },
  {
    id: 18,
    title: 'тест з математики',
    date: '2026-09-14',
    type: 'DEADLINE',
  },
  {
    id: 19,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-14',
    type: 'EVENT',
  },
  {
    id: 20,
    title: 'тест з математики',
    date: '2026-09-19',
    type: 'DEADLINE',
  },
  {
    id: 21,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-19',
    type: 'EVENT',
  },
  {
    id: 22,
    title: 'тест з математики',
    date: '2026-09-20',
    type: 'DEADLINE',
  },
  {
    id: 23,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-20',
    type: 'EVENT',
  },
  {
    id: 24,
    title: 'тест з математики',
    date: '2026-09-21',
    type: 'DEADLINE',
  },
  {
    id: 25,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-21',
    type: 'EVENT',
  },
  {
    id: 26,
    title: 'Назва завдання',
    date: '2026-09-22',
    type: 'DEADLINE',
    discipline: 'дисциплина',
    description: 'опис\nдедлайн',
    linkUrl: 'https://classroom.google.com/c/sample',
  },
  {
    id: 27,
    title: 'тест з математики',
    date: '2026-09-22',
    type: 'DEADLINE',
    discipline: 'Вища математика',
  },
  {
    id: 28,
    title: 'Вечірка у другому корпусі',
    date: '2026-09-22',
    type: 'EVENT',
    description: 'Вечірка у другому корпусі',
    time: '21.09.2198',
  },
  {
    id: 29,
    title: 'Вечірка у другому корпусі',
    date: '2026-09-22',
    type: 'EVENT',
    description: 'Вечірка у другому корпусі',
    time: '21.09.2198',
  },
  {
    id: 30,
    title: 'тест з математики',
    date: '2026-09-23',
    type: 'DEADLINE',
  },
  {
    id: 31,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-23',
    type: 'EVENT',
  },
  {
    id: 32,
    title: 'тест з математики',
    date: '2026-09-24',
    type: 'DEADLINE',
  },
  {
    id: 33,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-24',
    type: 'EVENT',
  },
  {
    id: 34,
    title: 'тест з математики',
    date: '2026-09-25',
    type: 'DEADLINE',
  },
  {
    id: 35,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-25',
    type: 'EVENT',
  },
  {
    id: 36,
    title: 'тест з математики',
    date: '2026-09-26',
    type: 'DEADLINE',
  },
  {
    id: 37,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-26',
    type: 'EVENT',
  },
  {
    id: 38,
    title: 'тест з математики',
    date: '2026-09-27',
    type: 'DEADLINE',
  },
  {
    id: 39,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-27',
    type: 'EVENT',
  },
  {
    id: 40,
    title: 'тест з математики',
    date: '2026-09-29',
    type: 'DEADLINE',
  },
  {
    id: 41,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-29',
    type: 'EVENT',
  },
  {
    id: 42,
    title: 'тест з математики',
    date: '2026-09-30',
    type: 'DEADLINE',
  },
  {
    id: 43,
    title: 'Вечірка у 2 корпусі',
    date: '2026-09-30',
    type: 'EVENT',
  },
  {
    id: 44,
    title: 'тест з математики',
    date: '2026-10-07',
    type: 'DEADLINE',
  },
  {
    id: 45,
    title: 'Хакатон',
    date: '2026-10-07',
    type: 'EVENT',
  },
];